# Generated by Django 4.2.8 on 2025-02-23 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('activityname', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'ActivityType',
                'verbose_name_plural': 'ActivityType',
            },
        ),
        migrations.CreateModel(
            name='Fitnessplan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('caloriestoconsume', models.CharField(blank=True, max_length=255, null=True)),
                ('caloriestoburn', models.CharField(blank=True, max_length=255, null=True)),
                ('carbs', models.CharField(blank=True, max_length=255, null=True)),
                ('protein', models.CharField(blank=True, max_length=255, null=True)),
                ('fat', models.CharField(blank=True, max_length=255, null=True)),
                ('sugar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Fitnessplan',
                'verbose_name_plural': 'Fitnessplan',
            },
        ),
        migrations.CreateModel(
            name='Nutritionlogging',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foodname', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nutritionlogging',
                'verbose_name_plural': 'Nutritionlogging',
            },
        ),
        migrations.CreateModel(
            name='Sleepmonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Sleepmonitoring',
                'verbose_name_plural': 'Sleepmonitoring',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Dailyactivity',
            fields=[
                ('activitydate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activitytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.activitytype')),
            ],
            options={
                'verbose_name': 'Dailyactivity',
                'verbose_name_plural': 'Dailyactivity',
            },
        ),
    ]
