# Generated by Django 4.2.8 on 2025-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepmonitoring',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
