# Generated by Django 4.2.8 on 2025-04-12 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dailyactivity_user_id_fitnessplan_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionlogging',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='logdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionlogging',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
