# Generated by Django 4.2.8 on 2025-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_nutritionmetrics_alter_nutritionlogging_foodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='weightLossOrGain',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
