# Generated by Django 4.2.8 on 2025-04-19 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fitnessplan_calories_fitnessplan_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='foodname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.nutritionmetrics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepmonitoring',
            name='logdate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sleepmonitoring',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
