# Generated by Django 4.2.8 on 2025-04-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fitnessplan_foodname_sleepmonitoring_logdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepmonitoring',
            name='logdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='FitnessDietPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diettype', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('foodname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nutritionmetrics')),
            ],
            options={
                'verbose_name': 'FitnessDietPlan',
                'verbose_name_plural': 'FitnessDietPlan',
            },
        ),
    ]
