# Generated by Django 4.2.8 on 2025-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_sleepmonitoring_logdate_fitnessdietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessplan',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='foodname',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='sugar',
        ),
    ]
